# Server
server.port=8081

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=consumer-group-1
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.value.default.type=consumer1.dto.InvoiceMessage
spring.kafka.consumer.properties.spring.json.trusted.packages=*
# ??????? ????? ???????? ???? ? Spring ??? ????????? ?? ????????? ??????

# Producer (??? ???????? ???????)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Logging
logging.level.com.billing=DEBUG
logging.level.org.springframework.kafka=DEBUG
logging.level.org.apache.kafka=DEBUG
logging.level.org.springframework.kafka.listener=DEBUG
logging.level.org.springframework.kafka.core=DEBUG